// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sduukpbovksrfuetxpvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdXVrcGJvdmtzcmZ1ZXR4cHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzk0MDQsImV4cCI6MjA3MjkxNTQwNH0.3K609xWL7fAi8AjBdysz97RYDBSfM0MLywUfOcxHxCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});